/*
 * GuiPrincipal.java
 * Interfaz grafica de ingreso de datos
 * Andrea Arguello 17801 Alejandro Tejada 17584
 * 3/11/2017
 */

import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Arrays;
/**
 *
 * @author Jose Tejada
 */
public class GuiPrincipal extends javax.swing.JFrame {
    private Acueducto acueducto;
    
    
    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
        acueducto=new Acueducto();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameNuevoTanque = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTipoTanque = new javax.swing.JComboBox<>();
        jTextFieldIdTanque = new javax.swing.JTextField();
        jTextFieldAnchoRadioTanque = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAltoTanque = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldLargoTanque = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldMunicipioValvula1 = new javax.swing.JTextField();
        jTextFieldHabitantesValvula1 = new javax.swing.JTextField();
        jTextFieldMunicipioValvula2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldHabitantesValvula2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldMunicipioValvula3 = new javax.swing.JTextField();
        jTextFieldHabitantesValvula3 = new javax.swing.JTextField();
        jTextFieldHabitantesValvula4 = new javax.swing.JTextField();
        jTextFieldMunicipioValvula4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldMunicipioValvula5 = new javax.swing.JTextField();
        jTextFieldMunicipioValvula6 = new javax.swing.JTextField();
        jTextFieldMunicipioValvula7 = new javax.swing.JTextField();
        jTextFieldMunicipioValvula8 = new javax.swing.JTextField();
        jTextFieldMunicipioValvula9 = new javax.swing.JTextField();
        jTextFieldMunicipioValvula10 = new javax.swing.JTextField();
        jTextFieldHabitantesValvula5 = new javax.swing.JTextField();
        jTextFieldHabitantesValvula6 = new javax.swing.JTextField();
        jTextFieldHabitantesValvula7 = new javax.swing.JTextField();
        jTextFieldHabitantesValvula8 = new javax.swing.JTextField();
        jTextFieldHabitantesValvula10 = new javax.swing.JTextField();
        jTextFieldHabitantesValvula9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButtonAgregarTanqueNuevo = new javax.swing.JButton();
        jFrameValvulas = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxIDTanque = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldMetrosTanque = new javax.swing.JTextField();
        jProgressBarAguaTanque = new javax.swing.JProgressBar();
        jButtonLlenarTanque = new javax.swing.JButton();
        jTextFieldMunicipio1 = new javax.swing.JTextField();
        jTextFieldMunicipio2 = new javax.swing.JTextField();
        jTextFieldMunicipio3 = new javax.swing.JTextField();
        jTextFieldMunicipio4 = new javax.swing.JTextField();
        jTextFieldMunicipio5 = new javax.swing.JTextField();
        jTextFieldMunicipio6 = new javax.swing.JTextField();
        jTextFieldMunicipio7 = new javax.swing.JTextField();
        jTextFieldMunicipio8 = new javax.swing.JTextField();
        jTextFieldMunicipio9 = new javax.swing.JTextField();
        jTextFieldMunicipio10 = new javax.swing.JTextField();
        jButtonAbrir1 = new javax.swing.JButton();
        jButtonAbrir2 = new javax.swing.JButton();
        jButtonAbrir3 = new javax.swing.JButton();
        jButtonAbrir4 = new javax.swing.JButton();
        jButtonAbrir5 = new javax.swing.JButton();
        jButtonAbrir6 = new javax.swing.JButton();
        jButtonAbrir7 = new javax.swing.JButton();
        jButtonAbrir8 = new javax.swing.JButton();
        jButtonAbrir9 = new javax.swing.JButton();
        jButtonAbrir10 = new javax.swing.JButton();
        jButtonCerrar1 = new javax.swing.JButton();
        jButtonCerrar2 = new javax.swing.JButton();
        jButtonCerrar3 = new javax.swing.JButton();
        jButtonCerrar4 = new javax.swing.JButton();
        jButtonCerrar5 = new javax.swing.JButton();
        jButtonCerrar6 = new javax.swing.JButton();
        jButtonCerrar7 = new javax.swing.JButton();
        jButtonCerrar8 = new javax.swing.JButton();
        jButtonCerrar9 = new javax.swing.JButton();
        jButtonCerrar10 = new javax.swing.JButton();
        jLabelCerrado1 = new javax.swing.JLabel();
        jLabelCerrado2 = new javax.swing.JLabel();
        jLabelCerrado3 = new javax.swing.JLabel();
        jLabelCerrado4 = new javax.swing.JLabel();
        jLabelCerrado5 = new javax.swing.JLabel();
        jLabelCerrado6 = new javax.swing.JLabel();
        jLabelCerrado7 = new javax.swing.JLabel();
        jLabelCerrado8 = new javax.swing.JLabel();
        jLabelCerrado9 = new javax.swing.JLabel();
        jLabelCerrado10 = new javax.swing.JLabel();
        jLabelAbierto1 = new javax.swing.JLabel();
        jLabelAbierto2 = new javax.swing.JLabel();
        jLabelAbierto3 = new javax.swing.JLabel();
        jLabelAbierto4 = new javax.swing.JLabel();
        jLabelAbierto5 = new javax.swing.JLabel();
        jLabelAbierto6 = new javax.swing.JLabel();
        jLabelAbierto7 = new javax.swing.JLabel();
        jLabelAbierto8 = new javax.swing.JLabel();
        jLabelAbierto9 = new javax.swing.JLabel();
        jLabelAbierto10 = new javax.swing.JLabel();
        jButtonSalirValvulas = new javax.swing.JButton();
        jFrameTanques = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTanques = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jButtonSalirTanques = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalirPrograma = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonAgregarTanque = new javax.swing.JButton();
        jButtonVerValvulas = new javax.swing.JButton();
        jButtonValvulasAbiertasCilindricos = new javax.swing.JButton();
        jButtonAguaDisponibleRegion = new javax.swing.JButton();
        jButtonVerTanquesRegistrados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jFrameNuevoTanque.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrameNuevoTanqueWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar Tanque");

        jLabel4.setText("Forma ");

        jLabel5.setText("Identificación");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Dimensiones");

        jComboBoxTipoTanque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cilindrico", "Ortogonal", "Cubico" }));
        jComboBoxTipoTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoTanqueActionPerformed(evt);
            }
        });

        jLabel7.setText("Ancho/Radio");

        jLabel8.setText("Alto");

        jLabel9.setText("Largo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxTipoTanque, 0, 171, Short.MAX_VALUE)
                                .addComponent(jTextFieldIdTanque))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnchoRadioTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAltoTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLargoTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTipoTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldIdTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldLargoTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAltoTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAnchoRadioTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ingreso Nuevo Tanque");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Agregar Válvulas");

        jLabel12.setText("No.");

        jLabel13.setText("Municipio");

        jLabel14.setText("Habitantes");

        jLabel15.setText("1");

        jLabel16.setText("2");

        jLabel17.setText("3");

        jLabel18.setText("4");

        jLabel19.setText("8");

        jLabel20.setText("7");

        jLabel21.setText("6");

        jLabel22.setText("5");

        jLabel23.setText("10");

        jLabel25.setText("9");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldMunicipioValvula2)
                            .addComponent(jTextFieldMunicipioValvula1)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldHabitantesValvula1)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextFieldHabitantesValvula2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMunicipioValvula3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jTextFieldMunicipioValvula4)
                            .addComponent(jTextFieldMunicipioValvula5)
                            .addComponent(jTextFieldMunicipioValvula6)
                            .addComponent(jTextFieldMunicipioValvula7)
                            .addComponent(jTextFieldMunicipioValvula8)
                            .addComponent(jTextFieldMunicipioValvula9)
                            .addComponent(jTextFieldMunicipioValvula10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldHabitantesValvula3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextFieldHabitantesValvula4)
                            .addComponent(jTextFieldHabitantesValvula5)
                            .addComponent(jTextFieldHabitantesValvula6)
                            .addComponent(jTextFieldHabitantesValvula7)
                            .addComponent(jTextFieldHabitantesValvula8)
                            .addComponent(jTextFieldHabitantesValvula10)
                            .addComponent(jTextFieldHabitantesValvula9))))
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldMunicipioValvula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jTextFieldHabitantesValvula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jTextFieldMunicipioValvula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldHabitantesValvula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jTextFieldMunicipioValvula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldHabitantesValvula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jTextFieldHabitantesValvula4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldMunicipioValvula4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMunicipioValvula5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabitantesValvula5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMunicipioValvula6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabitantesValvula6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMunicipioValvula7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabitantesValvula7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMunicipioValvula8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabitantesValvula8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMunicipioValvula9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabitantesValvula9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMunicipioValvula10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabitantesValvula10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAgregarTanqueNuevo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonAgregarTanqueNuevo.setText("Agregar Tanque");
        jButtonAgregarTanqueNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTanqueNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameNuevoTanqueLayout = new javax.swing.GroupLayout(jFrameNuevoTanque.getContentPane());
        jFrameNuevoTanque.getContentPane().setLayout(jFrameNuevoTanqueLayout);
        jFrameNuevoTanqueLayout.setHorizontalGroup(
            jFrameNuevoTanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameNuevoTanqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameNuevoTanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFrameNuevoTanqueLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonAgregarTanqueNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jFrameNuevoTanqueLayout.setVerticalGroup(
            jFrameNuevoTanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameNuevoTanqueLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAgregarTanqueNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFrameValvulas.setTitle("Valvulas");

        jLabel24.setText("Ingrese el Tanque");

        jComboBoxIDTanque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel26.setText("Cantidad de agua (m^3)");

        jTextFieldMetrosTanque.setEditable(false);

        jButtonLlenarTanque.setText("Llenar");

        jTextFieldMunicipio1.setEditable(false);

        jTextFieldMunicipio2.setEditable(false);

        jTextFieldMunicipio3.setEditable(false);

        jTextFieldMunicipio4.setEditable(false);

        jTextFieldMunicipio5.setEditable(false);

        jTextFieldMunicipio6.setEditable(false);

        jTextFieldMunicipio7.setEditable(false);

        jTextFieldMunicipio8.setEditable(false);

        jTextFieldMunicipio9.setEditable(false);

        jTextFieldMunicipio10.setEditable(false);

        jButtonAbrir1.setText("Abrir");

        jButtonAbrir2.setText("Abrir");

        jButtonAbrir3.setText("Abrir");

        jButtonAbrir4.setText("Abrir");

        jButtonAbrir5.setText("Abrir");

        jButtonAbrir6.setText("Abrir");

        jButtonAbrir7.setText("Abrir");

        jButtonAbrir8.setText("Abrir");

        jButtonAbrir9.setText("Abrir");

        jButtonAbrir10.setText("Abrir");

        jButtonCerrar1.setText("Cerrar");

        jButtonCerrar2.setText("Cerrar");

        jButtonCerrar3.setText("Cerrar");

        jButtonCerrar4.setText("Cerrar");

        jButtonCerrar5.setText("Cerrar");

        jButtonCerrar6.setText("Cerrar");

        jButtonCerrar7.setText("Cerrar");

        jButtonCerrar8.setText("Cerrar");

        jButtonCerrar9.setText("Cerrar");

        jButtonCerrar10.setText("Cerrar");

        jLabelCerrado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelCerrado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelCerrado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelCerrado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelCerrado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelCerrado6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelCerrado7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelCerrado8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelCerrado9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelCerrado10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/error.png"))); // NOI18N

        jLabelAbierto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        jLabelAbierto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        jLabelAbierto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        jLabelAbierto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        jLabelAbierto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        jLabelAbierto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        jLabelAbierto7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        jLabelAbierto8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        jLabelAbierto9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        jLabelAbierto10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/success.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxIDTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldMetrosTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jProgressBarAguaTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonLlenarTanque))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel24)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelAbierto10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCerrado10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jTextFieldMunicipio10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonAbrir10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCerrar10))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jTextFieldMunicipio9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonAbrir9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCerrar9))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jTextFieldMunicipio8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonAbrir8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCerrar8))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jTextFieldMunicipio7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonAbrir7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCerrar7))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jTextFieldMunicipio6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonAbrir6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCerrar6))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jTextFieldMunicipio5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonAbrir5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCerrar5))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jTextFieldMunicipio4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonAbrir4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCerrar4))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jTextFieldMunicipio1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonAbrir1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonCerrar1)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextFieldMunicipio2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAbrir2))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextFieldMunicipio3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAbrir3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCerrar3)
                                    .addComponent(jButtonCerrar2))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxIDTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldMetrosTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLlenarTanque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBarAguaTanque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir1)
                        .addComponent(jButtonCerrar1)
                        .addComponent(jLabelCerrado1))
                    .addComponent(jLabelAbierto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir2)
                        .addComponent(jButtonCerrar2))
                    .addComponent(jLabelCerrado2)
                    .addComponent(jLabelAbierto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir3)
                        .addComponent(jButtonCerrar3))
                    .addComponent(jLabelCerrado3)
                    .addComponent(jLabelAbierto3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir4)
                        .addComponent(jButtonCerrar4))
                    .addComponent(jLabelCerrado4)
                    .addComponent(jLabelAbierto4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir5)
                        .addComponent(jButtonCerrar5))
                    .addComponent(jLabelCerrado5)
                    .addComponent(jLabelAbierto5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir6)
                        .addComponent(jButtonCerrar6))
                    .addComponent(jLabelCerrado6)
                    .addComponent(jLabelAbierto6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir7)
                        .addComponent(jButtonCerrar7))
                    .addComponent(jLabelCerrado7)
                    .addComponent(jLabelAbierto7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir8)
                        .addComponent(jButtonCerrar8))
                    .addComponent(jLabelCerrado8)
                    .addComponent(jLabelAbierto8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir9)
                        .addComponent(jButtonCerrar9))
                    .addComponent(jLabelCerrado9)
                    .addComponent(jLabelAbierto9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMunicipio10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAbrir10)
                        .addComponent(jButtonCerrar10))
                    .addComponent(jLabelCerrado10)
                    .addComponent(jLabelAbierto10))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jButtonSalirValvulas.setText("Salir");

        javax.swing.GroupLayout jFrameValvulasLayout = new javax.swing.GroupLayout(jFrameValvulas.getContentPane());
        jFrameValvulas.getContentPane().setLayout(jFrameValvulasLayout);
        jFrameValvulasLayout.setHorizontalGroup(
            jFrameValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameValvulasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalirValvulas)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameValvulasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrameValvulasLayout.setVerticalGroup(
            jFrameValvulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameValvulasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalirValvulas)
                .addContainerGap())
        );

        jTextAreaTanques.setColumns(20);
        jTextAreaTanques.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTanques);

        jLabel27.setText("Tanques de la region");

        jButtonSalirTanques.setText("Salir");
        jButtonSalirTanques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirTanquesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameTanquesLayout = new javax.swing.GroupLayout(jFrameTanques.getContentPane());
        jFrameTanques.getContentPane().setLayout(jFrameTanquesLayout);
        jFrameTanquesLayout.setHorizontalGroup(
            jFrameTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameTanquesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jFrameTanquesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSalirTanques)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrameTanquesLayout.setVerticalGroup(
            jFrameTanquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameTanquesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalirTanques)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arguello y Tejada Inc.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acueducto Albear");

        jButtonSalirPrograma.setText("SALIR");
        jButtonSalirPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirProgramaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonAgregarTanque.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonAgregarTanque.setText("Agregar Tanque");
        jButtonAgregarTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTanqueActionPerformed(evt);
            }
        });

        jButtonVerValvulas.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonVerValvulas.setText("Ver Válvulas");
        jButtonVerValvulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerValvulasActionPerformed(evt);
            }
        });

        jButtonValvulasAbiertasCilindricos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonValvulasAbiertasCilindricos.setText("Válvulas Abiertas Cilíndricos");
        jButtonValvulasAbiertasCilindricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValvulasAbiertasCilindricosActionPerformed(evt);
            }
        });

        jButtonAguaDisponibleRegion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonAguaDisponibleRegion.setText("Agua Disponible Region");
        jButtonAguaDisponibleRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAguaDisponibleRegionActionPerformed(evt);
            }
        });

        jButtonVerTanquesRegistrados.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButtonVerTanquesRegistrados.setText("Ver Tanques Registrados");
        jButtonVerTanquesRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerTanquesRegistradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAgregarTanque, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerValvulas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAguaDisponibleRegion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonValvulasAbiertasCilindricos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerTanquesRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAgregarTanque, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButtonVerValvulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAguaDisponibleRegion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonValvulasAbiertasCilindricos, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButtonVerTanquesRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menú Principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalirPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalirPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirProgramaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirProgramaActionPerformed

    private void jButtonAgregarTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTanqueActionPerformed
        // TODO add your handling code here:
        jFrameNuevoTanque.pack();
        jFrameNuevoTanque.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarTanqueActionPerformed

    private void jButtonAgregarTanqueNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTanqueNuevoActionPerformed
        // TODO add your handling code here:
         String tipoTanqueEscogido=(String) jComboBoxTipoTanque.getSelectedItem();
         String idTanque=jTextFieldIdTanque.getText();
         ArrayList<Integer> habitantes= new ArrayList<>();
         ArrayList<String> municipios= new ArrayList<>();
         double radioTanque=0;
         double LargoTanque=0;
         double AltoTanque=0;
         
         switch (tipoTanqueEscogido.toUpperCase()) {
             case "CILINDRICO":
                 try {
                     radioTanque=Double.parseDouble(jTextFieldAnchoRadioTanque.getText());
                     AltoTanque=Double.parseDouble(jTextFieldAltoTanque.getText());
                     if (acueducto.verificarIDTanque(idTanque)==false) {
                         acueducto.agregarCilindrico(tipoTanqueEscogido, idTanque, AltoTanque, radioTanque, retornarListaMunicipios(), retornarListaHabitantes());
                         JOptionPane.showMessageDialog(null, "Tanque Agregado");
                     }
                     else if (acueducto.verificarIDTanque(idTanque)==true) {
                         JOptionPane.showMessageDialog(null, "El id del tanque ya existe, use otro.");
                     }
                 } catch (NumberFormatException e) {
                     JOptionPane.showMessageDialog(null, "Un valor o valores ingresados en el campo de Ancho/Radio o Alto no es numero.");
                     radioTanque=0;
                     LargoTanque=0;
                     AltoTanque=0;
                     tipoTanqueEscogido="";
                     idTanque="";
                     
                 }   break;
             case "CUBICO":
                 try {
                     radioTanque=Double.parseDouble(jTextFieldAnchoRadioTanque.getText());
                     if (acueducto.verificarIDTanque(idTanque)==false) {
                        acueducto.agregarCubico(tipoTanqueEscogido, idTanque, radioTanque, retornarListaMunicipios(), retornarListaHabitantes());
                     JOptionPane.showMessageDialog(null, "Tanque Agregado");
                     }
                     else if (acueducto.verificarIDTanque(idTanque)==true) {
                         JOptionPane.showMessageDialog(null, "El id del tanque ya existe, use otro.");
                     }
                 } catch (NumberFormatException e) {
                     JOptionPane.showMessageDialog(null, "El valor ingresado en el campo de Ancho/Radio no es un numero.");
                     radioTanque=0;
                     LargoTanque=0;
                     AltoTanque=0;
                     tipoTanqueEscogido="";
                     idTanque="";
                 }   break;
             case "ORTOGONAL":
                 try {
                     radioTanque=Double.parseDouble(jTextFieldAnchoRadioTanque.getText());
                     AltoTanque=Double.parseDouble(jTextFieldAltoTanque.getText());
                     LargoTanque=Double.parseDouble(jTextFieldLargoTanque.getText());
                     
                     if (acueducto.verificarIDTanque(idTanque)==false) {
                        acueducto.agregarCubico(tipoTanqueEscogido, idTanque, radioTanque, retornarListaMunicipios(), retornarListaHabitantes());
                     JOptionPane.showMessageDialog(null, "Tanque Agregado");
                     }
                     else if (acueducto.verificarIDTanque(idTanque)==true) {
                         JOptionPane.showMessageDialog(null, "El id del tanque ya existe, use otro.");
                     }
                 } catch (NumberFormatException e) {
                     JOptionPane.showMessageDialog(null, "Un valor o valores ingresados en el campo de Ancho/Radio, Alto o Largo no es numero.");
                     radioTanque=0;
                     LargoTanque=0;
                     AltoTanque=0;
                     tipoTanqueEscogido="";
                     idTanque="";
                 }   break;
             default:
                 break;
         }
         
              System.out.println("Informacion: "+ acueducto.getTanquesAcueducto());
    }//GEN-LAST:event_jButtonAgregarTanqueNuevoActionPerformed
    public ArrayList<Integer> retornarListaHabitantes(){
        ArrayList<Integer> habitantes= new ArrayList<>();
        try {
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula1.getText()));  
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula2.getText())); 
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula3.getText())); 
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula4.getText())); 
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula5.getText())); 
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula6.getText())); 
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula7.getText())); 
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula8.getText())); 
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula9.getText()));
          habitantes.add(Integer.parseInt(jTextFieldHabitantesValvula10.getText()));
          
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Un valor en el campo de habitantes es una letra o contiene letras, ingrese solo numero enteros.");
            habitantes.clear();
        }
        return habitantes;
    }
    
    public ArrayList<String> retornarListaMunicipios(){
        ArrayList<String> municipios= new ArrayList<>();
        try {
            municipios.add(jTextFieldMunicipioValvula1.getText());
            municipios.add(jTextFieldMunicipioValvula2.getText());
            municipios.add(jTextFieldMunicipioValvula3.getText());
            municipios.add(jTextFieldMunicipioValvula4.getText());
            municipios.add(jTextFieldMunicipioValvula5.getText());
            municipios.add(jTextFieldMunicipioValvula6.getText());
            municipios.add(jTextFieldMunicipioValvula7.getText());
            municipios.add(jTextFieldMunicipioValvula8.getText());
            municipios.add(jTextFieldMunicipioValvula9.getText());
            municipios.add(jTextFieldMunicipioValvula10.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error, ingrese de nuevo los valores de municipios.");
            municipios.clear();
        }
        return municipios;
    }
    private void jButtonVerValvulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerValvulasActionPerformed
        // TODO add your handling code here:
        jFrameValvulas.pack();
        jFrameValvulas.setVisible(true);
    }//GEN-LAST:event_jButtonVerValvulasActionPerformed

    private void jButtonAguaDisponibleRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAguaDisponibleRegionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Agua disponible para la region:\n" + String.valueOf(acueducto.getAguaRegion()) + "m^3");
    }//GEN-LAST:event_jButtonAguaDisponibleRegionActionPerformed

    private void jButtonValvulasAbiertasCilindricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValvulasAbiertasCilindricosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cantidad de valvulas de tanques cilindricos abiertas:\n"+String.valueOf(acueducto.valvulasAbiertasCilindro()));
    }//GEN-LAST:event_jButtonValvulasAbiertasCilindricosActionPerformed

    private void jFrameNuevoTanqueWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameNuevoTanqueWindowOpened
        // TODO add your handling code here:
        borrarCamposTanque();
    }//GEN-LAST:event_jFrameNuevoTanqueWindowOpened

    private void jComboBoxTipoTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoTanqueActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
         String a=null;
          a= (String) jComboBoxTipoTanque.getSelectedItem();//recogemos el dato que se seleccionó
          if (a.toUpperCase().equals("CILINDRICO")) {
              jTextFieldLargoTanque.setEditable(false);
             jTextFieldAnchoRadioTanque.setEditable(true);
             jTextFieldAltoTanque.setEditable(true);
          }
         else if ((a.toUpperCase().equals("ORTOGONAL"))) {
              jTextFieldLargoTanque.setEditable(true);
              jTextFieldAnchoRadioTanque.setEditable(true);
              jTextFieldAltoTanque.setEditable(true);
          }
         else if (a.toUpperCase().equals("CUBICO")) {
             jTextFieldLargoTanque.setEditable(false);
             jTextFieldAltoTanque.setEditable(false);
             jTextFieldAnchoRadioTanque.setEditable(true);
         }
         borrarCamposTanque();
    }//GEN-LAST:event_jComboBoxTipoTanqueActionPerformed

    private void jButtonVerTanquesRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerTanquesRegistradosActionPerformed
        // TODO add your handling code here:
        jFrameTanques.pack();
        jFrameTanques.setVisible(true);
        
        llenarInformacionTanques();
    }//GEN-LAST:event_jButtonVerTanquesRegistradosActionPerformed

    private void jButtonSalirTanquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirTanquesActionPerformed
        // TODO add your handling code here:
        
        jFrameTanques.setVisible(false);
    }//GEN-LAST:event_jButtonSalirTanquesActionPerformed

    public void llenarInformacionTanques(){
       jTextAreaTanques.setText("");
       jTextAreaTanques.append("INFORMACION DE TANQUES"); 
       jTextAreaTanques.append(System.getProperty("line.separator")); // Esto para el salto de línea 
       jTextAreaTanques.append(System.getProperty("line.separator")); // Esto para el salto de línea 
       jTextAreaTanques.append(acueducto.getTanquesAcueducto());
       
    }
    public void borrarCamposTanque(){
        jTextFieldLargoTanque.setText("");
         jTextFieldAnchoRadioTanque.setText("");
         jTextFieldAltoTanque.setText("");
         jTextFieldIdTanque.setText("");
     }
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipal().setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir1;
    private javax.swing.JButton jButtonAbrir10;
    private javax.swing.JButton jButtonAbrir2;
    private javax.swing.JButton jButtonAbrir3;
    private javax.swing.JButton jButtonAbrir4;
    private javax.swing.JButton jButtonAbrir5;
    private javax.swing.JButton jButtonAbrir6;
    private javax.swing.JButton jButtonAbrir7;
    private javax.swing.JButton jButtonAbrir8;
    private javax.swing.JButton jButtonAbrir9;
    private javax.swing.JButton jButtonAgregarTanque;
    private javax.swing.JButton jButtonAgregarTanqueNuevo;
    private javax.swing.JButton jButtonAguaDisponibleRegion;
    private javax.swing.JButton jButtonCerrar1;
    private javax.swing.JButton jButtonCerrar10;
    private javax.swing.JButton jButtonCerrar2;
    private javax.swing.JButton jButtonCerrar3;
    private javax.swing.JButton jButtonCerrar4;
    private javax.swing.JButton jButtonCerrar5;
    private javax.swing.JButton jButtonCerrar6;
    private javax.swing.JButton jButtonCerrar7;
    private javax.swing.JButton jButtonCerrar8;
    private javax.swing.JButton jButtonCerrar9;
    private javax.swing.JButton jButtonLlenarTanque;
    private javax.swing.JButton jButtonSalirPrograma;
    private javax.swing.JButton jButtonSalirTanques;
    private javax.swing.JButton jButtonSalirValvulas;
    private javax.swing.JButton jButtonValvulasAbiertasCilindricos;
    private javax.swing.JButton jButtonVerTanquesRegistrados;
    private javax.swing.JButton jButtonVerValvulas;
    private javax.swing.JComboBox<String> jComboBoxIDTanque;
    private javax.swing.JComboBox<String> jComboBoxTipoTanque;
    private javax.swing.JFrame jFrameNuevoTanque;
    private javax.swing.JFrame jFrameTanques;
    private javax.swing.JFrame jFrameValvulas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAbierto1;
    private javax.swing.JLabel jLabelAbierto10;
    private javax.swing.JLabel jLabelAbierto2;
    private javax.swing.JLabel jLabelAbierto3;
    private javax.swing.JLabel jLabelAbierto4;
    private javax.swing.JLabel jLabelAbierto5;
    private javax.swing.JLabel jLabelAbierto6;
    private javax.swing.JLabel jLabelAbierto7;
    private javax.swing.JLabel jLabelAbierto8;
    private javax.swing.JLabel jLabelAbierto9;
    private javax.swing.JLabel jLabelCerrado1;
    private javax.swing.JLabel jLabelCerrado10;
    private javax.swing.JLabel jLabelCerrado2;
    private javax.swing.JLabel jLabelCerrado3;
    private javax.swing.JLabel jLabelCerrado4;
    private javax.swing.JLabel jLabelCerrado5;
    private javax.swing.JLabel jLabelCerrado6;
    private javax.swing.JLabel jLabelCerrado7;
    private javax.swing.JLabel jLabelCerrado8;
    private javax.swing.JLabel jLabelCerrado9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBarAguaTanque;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaTanques;
    private javax.swing.JTextField jTextFieldAltoTanque;
    private javax.swing.JTextField jTextFieldAnchoRadioTanque;
    private javax.swing.JTextField jTextFieldHabitantesValvula1;
    private javax.swing.JTextField jTextFieldHabitantesValvula10;
    private javax.swing.JTextField jTextFieldHabitantesValvula2;
    private javax.swing.JTextField jTextFieldHabitantesValvula3;
    private javax.swing.JTextField jTextFieldHabitantesValvula4;
    private javax.swing.JTextField jTextFieldHabitantesValvula5;
    private javax.swing.JTextField jTextFieldHabitantesValvula6;
    private javax.swing.JTextField jTextFieldHabitantesValvula7;
    private javax.swing.JTextField jTextFieldHabitantesValvula8;
    private javax.swing.JTextField jTextFieldHabitantesValvula9;
    private javax.swing.JTextField jTextFieldIdTanque;
    private javax.swing.JTextField jTextFieldLargoTanque;
    private javax.swing.JTextField jTextFieldMetrosTanque;
    private javax.swing.JTextField jTextFieldMunicipio1;
    private javax.swing.JTextField jTextFieldMunicipio10;
    private javax.swing.JTextField jTextFieldMunicipio2;
    private javax.swing.JTextField jTextFieldMunicipio3;
    private javax.swing.JTextField jTextFieldMunicipio4;
    private javax.swing.JTextField jTextFieldMunicipio5;
    private javax.swing.JTextField jTextFieldMunicipio6;
    private javax.swing.JTextField jTextFieldMunicipio7;
    private javax.swing.JTextField jTextFieldMunicipio8;
    private javax.swing.JTextField jTextFieldMunicipio9;
    private javax.swing.JTextField jTextFieldMunicipioValvula1;
    private javax.swing.JTextField jTextFieldMunicipioValvula10;
    private javax.swing.JTextField jTextFieldMunicipioValvula2;
    private javax.swing.JTextField jTextFieldMunicipioValvula3;
    private javax.swing.JTextField jTextFieldMunicipioValvula4;
    private javax.swing.JTextField jTextFieldMunicipioValvula5;
    private javax.swing.JTextField jTextFieldMunicipioValvula6;
    private javax.swing.JTextField jTextFieldMunicipioValvula7;
    private javax.swing.JTextField jTextFieldMunicipioValvula8;
    private javax.swing.JTextField jTextFieldMunicipioValvula9;
    // End of variables declaration//GEN-END:variables
}
